apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    type: mysql
spec:
  containers:
  - name: mysql
    image: supergiantkir/animals:bear
    
-----------

apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    type: web
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - redis
        topologyKey: kubernetes.io/hostname
  containers:
  - name: web
    image: supergiantkir/animals:bear

----------

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    type: redis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
  containers:
  - name: redis
    image: supergiantkir/animals:bear
